package com.renhou.model;

public enum MeldTag { // For use in the tagging process of tagHand() and listYaku()
    
    // Meld specific tags (need to reference a meld)
    MELDMAN, MELDPIN, MELDSOU,
    MELDSIMPLES, MELDTERMINAL, MELDHONORS,  // MELDTERMINAL counts terminal chiis
    MELDCHII, MELDPON, MELDKAN,
    MELDOPEN, MELDCLOSED,
    MELDSEATWIND, MELDROUNDWIND, MELDDRAGON,
    MELDGREEN,
    WAITRYANMEN, WAITSHANPON, WAITKANCHAN, WAITPENCHAN,
    
    // Pair specific tags
    PAIRMAN, PAIRPIN, PAIRSOU,
    PAIRSIMPLES, PAIRTERMINALS, PAIRHONORS,
    PAIRSEATWIND, PAIRROUDNWIND, PAIRDRAGON,
    PAIRGREEN,
    WAITTANKI,
    
    // General Hand Tags (meta tags derived from meld/pair tags)
    HANDMAN, HANDPIN, HANDSOU,
    HANDSIMPLES, HANDTERMINALS, HANDHONORS,
    HANDCHII, HANDNOCHII, HANDKAN,
    HANDOPEN, HANDCLOSED,
    HANDNOMAN, HANDNOPIN, HANDNOSOU,
    HANDGREEN,
    
    // Special exceptions
    ALLPAIRS, KOKUSHI, IIPEIKOU, SANSHOKUDOUJUN, ITTSUU,
    RYANPEIKOU, SANSHOKUDOUKOU, CHUURENPOUTOU, JUNSEICHUURENPOUTOU
}
